-- 초기화
SELECT 'DROP TABLE "' || TABLE_NAME || '" CASCADE CONSTRAINTS;' FROM user_tables;
DROP TABLE "EMP" CASCADE CONSTRAINTS;
DROP TABLE "CUSTOMER" CASCADE CONSTRAINTS;
CREATE TABLE EMP (
    NO   NUMBER,
    NAME VARCHAR2(20),
    AGE  NUMBER
);
CREATE TABLE CUSTOMER (
    ID      NUMBER PRIMARY KEY,
    NAME    VARCHAR2(20) NOT NULL,
    ADDRESS VARCHAR2(100)
);
-- 예제3. 주문 테이블
CREATE TABLE ORDERS (
    ORDER_ID    NUMBER PRIMARY KEY,
    SALESMAN_ID NUMBER,
    ORDER_DATE  DATE NOT NULL
);
-- 초기화 끝

-- 예제1. CUSTOMER 테이블에 성별 컬럼 추가
ALTER TABLE CUSTOMER ADD GENDER VARCHAR2(9);	-- 컬럼 추가

-- 예제2. 컬럼이름 바꾸기
ALTER TABLE CUSTOMER RENAME COLUMN GENDER TO GEN; -- 이름 변경
ALTER TABLE CUSTOMER RENAME COLUMN GEN TO GENDER; -- 원복

-- 예제3. 컬럼크기 바꾸기
ALTER TABLE CUSTOMER MODIFY GENDER VARCHAR2(100);
ALTER TABLE CUSTOMER MODIFY GENDER VARCHAR2(100) DEFAULT 'NONE' NOT NULL;

-- 예제4. 컬럼 자료형/제약조건 바꾸기
ALTER TABLE CUSTOMER MODIFY GENDER NUMBER;	-- 자료형 변경
ALTER TABLE CUSTOMER MODIFY GENDER NOT NULL;    -- NOT NULL 제약조건 변경

-- 예제5. 컬럼에 설명 달기
COMMENT ON COLUMN CUSTOMER.GENDER IS '성별';  -- 설명 달기

-- 예제6. 컬럼 삭제
ALTER TABLE CUSTOMER DROP COLUMN NAME;
ALTER TABLE CUSTOMER DROP COLUMN ADDRESS;
ALTER TABLE CUSTOMER DROP COLUMN GENDER;

-- 퀴즈1~3. EMP 테이블 구조 변경 
ALTER TABLE EMP ADD SALARY NUMBER;
ALTER TABLE EMP MODIFY SALARY NOT NULL; 

COMMENT ON COLUMN EMP.NO IS '직원번호';
COMMENT ON COLUMN EMP.NAME IS '이름';
COMMENT ON COLUMN EMP.AGE IS '나이';
COMMENT ON COLUMN EMP.SALARY IS '월급';

-- 퀴즈4~8. ORDERS 테이블 구조 변경 
ALTER TABLE ORDERS ADD CUSTOMER_NAME VARCHAR2(50) NOT NULL;

ALTER TABLE ORDERS MODIFY SALESMAN_ID VARCHAR2(50);
ALTER TABLE ORDERS RENAME COLUMN SALESMAN_ID TO SALESMAN_NAME;

ALTER TABLE ORDERS MODIFY ORDER_DATE NULL;

COMMENT ON COLUMN ORDERS.ORDER_ID IS '직원아이디';
COMMENT ON COLUMN ORDERS.SALESMAN_NAME IS '판매원이름';
COMMENT ON COLUMN ORDERS.ORDER_DATE IS '주문날짜';
COMMENT ON COLUMN ORDERS.CUSTOMER_NAME IS '고객이름';




