------------- 초기화 ----------------
DROP TABLE ACADEMY_A;
DROP TABLE ACADEMY_B;
------------- 초기화 끝 --------------

-- 예제1. A학원테이블만들고 데이터 넣기
CREATE TABLE ACADEMY_A (
    STUDENT_NO      NUMBER PRIMARY KEY,
    STUDENT_NAME    VARCHAR2(20) NOT NULL
);
INSERT INTO ACADEMY_A VALUES (1001, '정소화');
INSERT INTO ACADEMY_A VALUES (1002, '김용욱');
INSERT INTO ACADEMY_A VALUES (1003, '고명석');
INSERT INTO ACADEMY_A VALUES (1004, '김연아');
-- 예제2. B학원테이블만들고 데이터 넣기
CREATE TABLE ACADEMY_B (
    STUDENT_NO      NUMBER PRIMARY KEY,
    STUDENT_NAME    VARCHAR2(20) NOT NULL
);
INSERT INTO ACADEMY_B VALUES (1003, '고명석');
INSERT INTO ACADEMY_B VALUES (1004, '김연아');
INSERT INTO ACADEMY_B VALUES (1005, '김태환');
INSERT INTO ACADEMY_B VALUES (1006, '이윤아');

-- 예제3-1. A학원과 B학원 테이블 조인하여 조회하기
SELECT * 
FROM ACADEMY_A T1, ACADEMY_B T2
WHERE T1.STUDENT_NO = T2.STUDENT_NO;

SELECT T1.STUDENT_NAME, T1.STUDENT_NO 
FROM ACADEMY_A T1, ACADEMY_B T2
WHERE T1.STUDENT_NO = T2.STUDENT_NO;

--NONE EQUI
SELECT *
FROM ACADEMY_A T1, ACADEMY_B T2
WHERE T1.STUDENT_NO >= 1003;

-- 예제3-2. A학원과 B학원 테이블 조인하여 조회하기
SELECT * 
FROM ACADEMY_A T1
JOIN ACADEMY_B T2
ON (T1.STUDENT_NO = T2.STUDENT_NO);

-- 예제1. A학원과 B학원 테이블 OUTER 조인하여 조회하기
SELECT T1.STUDENT_NO, T1.STUDENT_NAME, T2.STUDENT_NO, T2.STUDENT_NAME
FROM ACADEMY_A T1
FULL OUTER JOIN ACADEMY_B T2
ON (T1.STUDENT_NO = T2.STUDENT_NO)
ORDER BY T1.STUDENT_NO;

-- 예제1. A학원과 B학원 테이블 LEFT 조인하여 조회하기
SELECT * 
FROM ACADEMY_A T1
LEFT JOIN ACADEMY_B T2
ON (T1.STUDENT_NO = T2.STUDENT_NO)
ORDER BY T1.STUDENT_NO;

-- 예제1. A학원과 B학원 테이블 RIGHT 조인하여 조회하기
SELECT * 
FROM ACADEMY_A T1
RIGHT JOIN ACADEMY_B T2
ON (T1.STUDENT_NO = T2.STUDENT_NO)
ORDER BY T1.STUDENT_NO;

-- 예제1. A학원과 B학원 테이블 NATURAL 조인 하여 조회하기
SELECT * 
FROM ACADEMY_A T1
NATURAL JOIN ACADEMY_B T2;

-- 퀴즈1. 부서 테이블과 직원 테이블을 조인하여 아래와 같은 결과를 출력하시오
SELECT T1.DEPT_NAME, T2.EMP_NAME
FROM DEPT T1
JOIN EMP T2
ON (T1.DEPT_NO = T2.DEPT_NO);

-- 퀴즈2. 학생/수업/수강 테이블을 조인하여 아래와 같은 결과를 출력하시오 
SELECT T3.STUDENT_NO, T3.STUDENT_NAME, T2.CLASS_NAME
FROM CLASS_STUDENT T1
JOIN CLASS T2
ON (T1.CLASS_NO = T2.CLASS_NO)
JOIN STUDENT T3
ON (T1.STUDENT_NO = T3.STUDENT_NO);
-- 혹은
SELECT T3.STUDENT_NO, T3.STUDENT_NAME, T2.CLASS_NAME
FROM CLASS_STUDENT T1, CLASS T2, STUDENT T3
WHERE (T1.CLASS_NO = T2.CLASS_NO)
AND (T1.STUDENT_NO = T3.STUDENT_NO);

-- 예제1. A학원과 B학원 테이블 UNIONALL하여 조회하기
SELECT * 
FROM ACADEMY_A
UNION ALL
SELECT * 
FROM ACADEMY_B;

-- 예제2. A학원과 B학원 테이블 UNION하고 중복을 제거하여 조회하기
SELECT * 
FROM ACADEMY_A
UNION
SELECT * 
FROM ACADEMY_B;

-- 예제3. A학원과 B학원 테이블 INTERSECT하여 조회하기
SELECT * 
FROM ACADEMY_A
INTERSECT
SELECT * 
FROM ACADEMY_B;

-- 예제4. A학원과 B학원 테이블 MINUS하여 조회하기
SELECT * 
FROM ACADEMY_A
MINUS
SELECT * 
FROM ACADEMY_B;

