----권한-----
CREATE USER PERSON1 IDENTIFIED BY TEST1234;
GRANT CONNECT, RESOURCE, DBA TO PERSON1; --권한 부여
ALTER USER PERSON1 IDENTIFIED BY TEST6789;
DROP USER PERSON1;

-----커밋, 롤백-----


CREATE TABLE SAMPLE (
    NO   NUMBER PRIMARY KEY,
    NAME VARCHAR2(20),
    AGE  NUMBER
);

INSERT INTO SAMPLE VALUES(1, '양지은', 10);
INSERT INTO SAMPLE VALUES(2, '박우진', 10);
INSERT INTO SAMPLE VALUES(3, '김태은', 10);

COMMIT;

INSERT INTO SAMPLE VALUES(4, '정지우', 10);

ROLLBACK;


ALTER TABLE SAMPLE MODIFY AGE NUMBER CHECK(AGE IN (10, 11));
INSERT INTO SAMPLE VALUES(4, '정지우', 12); --에러발생

---인덱스----

--초기화
TRUNCATE TABLE EMP;

INSERT INTO EMP (NO, NAME, AGE) VALUES (1, '둘리', 10);
INSERT INTO EMP (NO, NAME, AGE) VALUES (2, '고길동', 10);
INSERT INTO EMP (NO, NAME, AGE) VALUES (3, '또치', 10);

CREATE INDEX EMP_IX01 ON EMP(NAME);
CREATE INDEX EMP_IX02 ON EMP(NO, NAME);
DROP INDEX EMP_IX02;

CREATE UNIQUE INDEX EMP_UK ON EMP(AGE); --에러 해당 테이블의 유일한 값이여야 한다.
CREATE UNIQUE INDEX EMP_UK ON EMP(NO);


--프로시저-------------

--CREATE OR REPLACE PROCEDURE EX_PROC
--(
--   in_type IN VARCHAR2,
--   in_name IN VARCHAR2
--)
--IS
--price NUMBER := 10000;
--
--BEGIN
--
--INSERT INTO GIFT
--VALUES (11, in_type, in_name, price);
--COMMIT;
--
--END EX_PROC;

--EXEC EX_PROC('가전제품','TV');

DROP PROCEDURE EX_PROC;