--문자 함수

SELECT CHR(65) FROM DUAL;
SELECT LOWER('JENNIE') FROM DUAL;
SELECT UPPER('jennie') FROM DUAL;
SELECT LTRIM('    JENNIE') FROM DUAL;
SELECT LTRIM('블랙핑크', '블랙') FROM DUAL;
SELECT RTRIM('JENNIE    ') FROM DUAL;
SELECT RTRIM('블랙핑크', '핑크') FROM DUAL;
SELECT TRIM('    JENNIE    ') FROM DUAL;
SELECT TRIM(LEADING '블' FROM '블랙핑크') FROM DUAL;
SELECT TRIM(TRAILING '크' FROM '블랙핑크') FROM DUAL;
SELECT TRIM(BOTH '블' FROM '블랙핑크블') FROM DUAL;

SELECT SUBSTR('블랙핑크제니', 3, 2) FROM DUAL; 
SELECT SUBSTR('블랙핑크제니', 3, 4) FROM DUAL; 
SELECT LENGTH('JENNIE') FROM DUAL; 
SELECT LENGTH('블랙핑크') FROM DUAL; 
SELECT REPLACE('블랙핑크제니', '제니', '지수') FROM DUAL;
SELECT REPLACE('블랙핑크제니', '블랙') FROM DUAL;


--숫자 함수

SELECT ABS(-1) FROM DUAL;
SELECT ABS(2) FROM DUAL;
SELECT SIGN(-5) FROM DUAL;
SELECT SIGN(5) FROM DUAL;
SELECT SIGN(0) FROM DUAL;
SELECT ROUND(163.76, 1) FROM DUAL;
SELECT ROUND(163.76, -2) FROM DUAL;
SELECT TRUNC(54.29, 1) FROM DUAL;
SELECT TRUNC(54.29, -2) FROM DUAL;
SELECT CEIL(72.86) FROM DUAL;
SELECT CEIL(-33.4) FROM DUAL;
SELECT FLOOR(22.3) FROM DUAL;
SELECT FLOOR(-22.3) FROM DUAL;
SELECT MOD(15, 7) FROM DUAL;
SELECT MOD(15, -4) FROM DUAL;

--날짜 함수

SELECT SYSDATE FROM DUAL;
SELECT EXTRACT(YEAR FROM SYSDATE) AS YEAR,
               EXTRACT(MONTH FROM SYSDATE) AS MONTH,
               EXTRACT(DAY FROM SYSDATE) AS DAY
FROM DUAL;

SELECT ADD_MONTHS(TO_DATE('2021-12-31', 'YYYY-MM-DD'), -1) AS PRE,
               ADD_MONTHS(TO_DATE('2021-12-31', 'YYYY-MM-DD'), 1) AS NEXT
FROM DUAL;

--명시적 변환 함수

SELECT TO_NUMBER('1234') FROM DUAL;
--SELECT TO_NUMBER('ADC') FROM DUAL;
SELECT TO_CHAR(1234) FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'YYYYMMDD HH24MISS') FROM DUAL;
SELECT TO_DATE('20210602', 'YYYYMMDD') FROM DUAL;

--NULL관련 함수

SELECT NAME, NVL(ADDRESS, '주소없음') AS ADDRESS FROM CUSTOMER;
SELECT NAME, NULLIF(ADDRESS, '인천') AS ADDRESS FROM CUSTOMER;
SELECT NAME, COALESCE(NAME, ADDRESS) AS DD FROM CUSTOMER;

--DECODE

SELECT ID, DECODE(ID, 1, 'BLUE', 2, 'RED', 3, 'YELLOW', 4, 'BLACK', 5, 'WHITE') FROM CUSTOMER;

SELECT ID
     , CASE WHEN ID = 1 THEN 'BLUE'
            WHEN ID = 2 THEN 'RED'
            WHEN ID = 3 THEN 'YELLOW'
            WHEN ID = 4 THEN 'BLACK'
            ELSE 'WHITE'
       END AS TEST
  FROM CUSTOMER;



--퀴즈1

--퀴즈2

--퀴즈3

--퀴즈4

--퀴즈5

--퀴즈6

